import { Medicine, Substitute } from "@/types"

export const medicines: Medicine[] = [
  {
    id: "panadol-500",
    name: "Panadol",
    genericName: "Paracetamol",
    salt: "Paracetamol",
    manufacturer: "GSK",
    estimatedPrice: 30,
    type: "tablet",
    strength: "500mg",
    uses: "Treats mild to moderate pain and fever.",
    sideEffects: ["Nausea", "Allergic reactions"],
  },
  {
    id: "brufen-400",
    name: "Brufen",
    genericName: "Ibuprofen",
    salt: "Ibuprofen",
    manufacturer: "Abbott",
    estimatedPrice: 45,
    type: "tablet",
    strength: "400mg",
    uses: "Relieves pain, inflammation, and fever.",
    sideEffects: ["Stomach upset", "Dizziness"],
  },
  {
    id: "augmentin-625",
    name: "Augmentin",
    genericName: "Co-Amoxiclav",
    salt: "Amoxicillin + Clavulanic Acid",
    manufacturer: "GSK",
    estimatedPrice: 350,
    type: "tablet",
    strength: "625mg",
    uses: "Treats various bacterial infections.",
    sideEffects: ["Diarrhea", "Skin rash"],
  },
  {
    id: "disprin-300",
    name: "Disprin",
    genericName: "Aspirin",
    salt: "Aspirin",
    manufacturer: "Reckitt",
    estimatedPrice: 25,
    type: "tablet",
    strength: "300mg",
    uses: "Pain relief and blood thinner.",
    sideEffects: ["Stomach irritation", "Bleeding"],
  },
  {
    id: "flagyl-400",
    name: "Flagyl",
    genericName: "Metronidazole",
    salt: "Metronidazole",
    manufacturer: "Sanofi",
    estimatedPrice: 60,
    type: "tablet",
    strength: "400mg",
    uses: "Treats infections caused by bacteria or parasites.",
    sideEffects: ["Metallic taste", "Nausea"],
  },
]

export const substitutes: Record<string, Substitute[]> = {
  "panadol-500": [
    {
      id: "calpol-500",
      name: "Calpol",
      salt: "Paracetamol",
      manufacturer: "GSK",
      estimatedPrice: 28,
      strength: "500mg",
      type: "tablet",
      priceComparison: "cheaper",
      availability: "high",
      rating: 4.8,
    },
    {
      id: "febrol-500",
      name: "Febrol",
      salt: "Paracetamol",
      manufacturer: "Sami",
      estimatedPrice: 25,
      strength: "500mg",
      type: "tablet",
      priceComparison: "cheaper",
      availability: "high",
      rating: 4.5,
    },
    {
      id: "panpara-500",
      name: "Panpara",
      salt: "Paracetamol",
      manufacturer: "Platinum",
      estimatedPrice: 24,
      strength: "500mg",
      type: "tablet",
      priceComparison: "cheaper",
      availability: "medium",
      rating: 4.2,
    },
  ],
  "brufen-400": [
    {
      id: "advil-400",
      name: "Advil",
      salt: "Ibuprofen",
      manufacturer: "Pfizer",
      estimatedPrice: 50,
      strength: "400mg",
      type: "tablet",
      priceComparison: "expensive",
      availability: "medium",
      rating: 4.9,
    },
    {
      id: "profen-400",
      name: "Profen",
      salt: "Ibuprofen",
      manufacturer: "Sami",
      estimatedPrice: 40,
      strength: "400mg",
      type: "tablet",
      priceComparison: "cheaper",
      availability: "high",
      rating: 4.6,
    },
  ],
  "augmentin-625": [
    {
      id: "amoxil-cv-625",
      name: "Amoxil CV",
      salt: "Amoxicillin + Clavulanic Acid",
      manufacturer: "GSK",
      estimatedPrice: 340,
      strength: "625mg",
      type: "tablet",
      priceComparison: "cheaper",
      availability: "high",
      rating: 4.7,
    },
    {
      id: "mox-625",
      name: "Mox",
      salt: "Amoxicillin + Clavulanic Acid",
      manufacturer: "Getz",
      estimatedPrice: 320,
      strength: "625mg",
      type: "tablet",
      priceComparison: "cheaper",
      availability: "medium",
      rating: 4.5,
    },
  ],
}
