import { Medicine, Substitute } from "@/types"

export const medicines: Medicine[] = [
  {
    id: "panadol-500",
    name: "Panadol",
    genericName: "Paracetamol",
    salt: "Paracetamol",
    manufacturer: "GSK",
    price: 30,
    type: "tablet",
    strength: "500mg",
  },
  {
    id: "brufen-400",
    name: "Brufen",
    genericName: "Ibuprofen",
    salt: "Ibuprofen",
    manufacturer: "Abbott",
    price: 45,
    type: "tablet",
    strength: "400mg",
  },
  {
    id: "augmentin-625",
    name: "Augmentin",
    genericName: "Co-Amoxiclav",
    salt: "Amoxicillin + Clavulanic Acid",
    manufacturer: "GSK",
    price: 350,
    type: "tablet",
    strength: "625mg",
  },
  {
    id: "disprin-300",
    name: "Disprin",
    genericName: "Aspirin",
    salt: "Aspirin",
    manufacturer: "Reckitt",
    price: 25,
    type: "tablet",
    strength: "300mg",
  },
  {
    id: "flagyl-400",
    name: "Flagyl",
    genericName: "Metronidazole",
    salt: "Metronidazole",
    manufacturer: "Sanofi",
    price: 60,
    type: "tablet",
    strength: "400mg",
  },
]

export const substitutes: Record<string, Substitute[]> = {
  "panadol-500": [
    {
      id: "calpol-500",
      name: "Calpol",
      salt: "Paracetamol",
      manufacturer: "GSK",
      price: 28,
      priceComparison: "cheaper",
      availability: "high",
      rating: 4.8,
    },
    {
      id: "febrol-500",
      name: "Febrol",
      salt: "Paracetamol",
      manufacturer: "Sami",
      price: 25,
      priceComparison: "cheaper",
      availability: "high",
      rating: 4.5,
    },
    {
      id: "panpara-500",
      name: "Panpara",
      salt: "Paracetamol",
      manufacturer: "Platinum",
      price: 24,
      priceComparison: "cheaper",
      availability: "medium",
      rating: 4.2,
    },
  ],
  "brufen-400": [
    {
      id: "advil-400",
      name: "Advil",
      salt: "Ibuprofen",
      manufacturer: "Pfizer",
      price: 50,
      priceComparison: "expensive",
      availability: "medium",
      rating: 4.9,
    },
    {
      id: "profen-400",
      name: "Profen",
      salt: "Ibuprofen",
      manufacturer: "Sami",
      price: 40,
      priceComparison: "cheaper",
      availability: "high",
      rating: 4.6,
    },
  ],
  "augmentin-625": [
    {
      id: "amoxil-cv-625",
      name: "Amoxil CV",
      salt: "Amoxicillin + Clavulanic Acid",
      manufacturer: "GSK",
      price: 340,
      priceComparison: "cheaper",
      availability: "high",
      rating: 4.7,
    },
    {
      id: "mox-625",
      name: "Mox",
      salt: "Amoxicillin + Clavulanic Acid",
      manufacturer: "Getz",
      price: 320,
      priceComparison: "cheaper",
      availability: "medium",
      rating: 4.5,
    },
  ],
}
